site_name: Fine Weather
site_description: Fine Weather is a photo album application based on [Vue](https://github.com/vuejs/core) and [BootstrapFlask](https://github.com/helloflask/bootstrap-flask), which is built to collect fine-weather moments of life.
site_url: https://codekitchen-community.github.io/fine-weather/
docs_dir: docs
theme:
  language: en
  name: material
  palette:
    primary: deep-orange
    accent: amber
    theme: default
  features:
    - navigation.footer
  favicon: _assets/fine-weather-gallery.ico
repo_url: https://github.com/codekitchen-community/fine-weather
repo_name: codekitchen-community/fine-weather
copyright: Copyright © 2024 代码厨房 - 编程和开源爱好者社区
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Changelog: changelog.md
  - License: license.md
    

plugins:
  - search:
      lang: 
        - en
        - zh
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true