name: Documentation Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Move manager out
        run: mv ./manager/* ./
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.12'
          cache: true
      - name: Install dependencies
        run: pdm install -Gdoc
      - name: Build documentation
        run: pdm run mkdocs build --clean
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: site
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
